### ISSUE TITLE
logstash logs?

### ISSUE THREAD

**Issue by kotter** [helderco/docker-elk#1]
Hello-

I'm using your image here for testing, and I have not been able to find out how or if there are any logfiles available that would explain why my logstash docker instance quits processing at random times.  Hopefully you may be able to assist me quickly with this, as I cannot find any logstash logs in /var/log or /opt/logstash.

Many thanks-

**Comment by helderco** [comment]
Sorry for the late response :\

Have you figured it out?

**Comment by kotter** [comment]
@helderco yes, I'm looking good at this point- didn't realize this was still dangling out here...
